### ISSUE TITLE
Does not work with Ruby 1.9+?

### ISSUE THREAD

**Issue by weakish** [danielribeiro/RubyUnderscore#2]
Since RubyUnderscore uses ParseTree, it will not work with Ruby 1.9+?

How to make it compatible with Ruby 1.9+? (I'm using 2.1 now.)
Replace ParseTree with [sourcify](https://github.com/ngty/sourcify)?

**Comment by danielribeiro** [comment]
Thanks for the reminder. Does sourcify works with 2.1?

**Comment by weakish** [comment]
Haven't tried it.
AFAIK, sourcify uses ruby_parser for Ruby 1.9+.
And ruby_parser has only initial support of Ruby 2.1.

**Comment by danielribeiro** [comment]
Ok. It seems to work with 2.0 and when I have time I'll try it with 2.1. If it all goes well, should be fairly easy change: updating ruby2ruby and change this line: https://github.com/danielribeiro/RubyUnderscore/blob/master/lib/tree_converters.rb#L51

**Comment by weakish** [comment]
> when I have time I'll try it with 2.1

I've tried. It seems work with 2.1.

> should be fairly easy change: updating ruby2ruby and change this line

I've changed this line.
I use `ruby_parser` (`sourcify` uses it underhood. `ruby_parser` is more suitable here, since it provides more low level functions.)
I'm sure the output it given is identical to ParseTree.translate.
But when testing with the example given on README, it gives this error:

``` sh
; cat >> testrb_.rb                                                              
class MethodFinder
  include RubyUnderscore::Base

  def find_interrogation_methods
    [String, Array, Class].map(_.public_instance_methods.grep /d\?$/).flatten.sort.uniq
  end
end
p MethodFinder.new.find_interrogation_methods

; ruby testrb_.rb
/var/lib/gems/2.1.0/gems/ruby_parser-3.6.3/lib/ruby_parser_extras.rb:1025:in `block in pro
cess': bad val: Kls (RuntimeError)
```

I'm not sure what causes this error?
Because `ruby_parser` is much slower than ParseTree, so it times out?

Ref:
- the broken branch [weakish/ruby_parser](https://github.com/weakish/RubyUnderscore/commit/1eade285ad91d8da8c7d9d165c86ec6529ac7f48)
- [ruby_parser's `bad val` doc](http://docs.seattlerb.org/ruby_parser/RubyParserStuff.html#method-i-process)
